// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEjhY4ky1gGjfXbIAdDAtV24KfYghwwAk',
    appId: '1:1038776967097:web:942d864a577c4650fbe068',
    messagingSenderId: '1038776967097',
    projectId: 'liturgical-app',
    authDomain: 'liturgical-app.firebaseapp.com',
    storageBucket: 'liturgical-app.firebasestorage.app',
    measurementId: 'G-5HNL1EVGMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6T9hZY0dYxI_9f2wVBMH1q3pcyF7Mcuc',
    appId: '1:1038776967097:android:e68884e7b69484defbe068',
    messagingSenderId: '1038776967097',
    projectId: 'liturgical-app',
    storageBucket: 'liturgical-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhePA9vN7oMbxvAODcOzInAdXf710sXxU',
    appId: '1:1038776967097:ios:42e6e8d6f3201104fbe068',
    messagingSenderId: '1038776967097',
    projectId: 'liturgical-app',
    storageBucket: 'liturgical-app.firebasestorage.app',
    iosClientId: '1038776967097-mnirnghlgfhe3bvk4la90jva12senug7.apps.googleusercontent.com',
    iosBundleId: 'com.example.zpasjidoliturgii',
  );
}
